import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { SimplePracticeClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/health.js';
import { tempStore } from './helpers.js';

/**
 * A CDN/WAF block is not an expired session (chrischall/mcp-host#1015).
 *
 * The client used to drop a non-JSON error body and turn every 401/403 into
 * "The portal session has expired", which the healthcheck classifier then
 * reported as `session_expired` — sending the user to re-sign in when the
 * edge refused the request before the portal ever saw the cookie. These run
 * the REAL client against the page CloudFront serves.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  'Request blocked. We can\'t connect to the server for this app or website at this time. ' +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function blocked(): Response {
  return {
    ok: false,
    status: 403,
    statusText: 'Forbidden',
    headers: new Headers({
      'content-type': 'text/html',
      'x-cache': 'Error from cloudfront',
      server: 'CloudFront',
    }),
    text: async () => CLOUDFRONT_BLOCK,
  } as unknown as Response;
}

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint: string;
}

async function healthcheck(response: () => Response): Promise<Result> {
  const fetchImpl = (async () => response()) as unknown as typeof fetch;
  const client = new SimplePracticeClient({ fetchImpl, store: tempStore() });
  client.saveSession('simplepractice-session=abc123');
  const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
  const res = await h.client.callTool({ name: 'simplepractice_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

describe('a CloudFront block reads as edge_blocked, not an expired session', () => {
  const saved = { ...process.env };
  beforeEach(() => {
    process.env.SIMPLEPRACTICE_PRACTICE = 'achievebalancetherapy';
  });
  afterEach(() => {
    process.env = { ...saved };
  });

  it('on the healthcheck probe', async () => {
    const r = await healthcheck(blocked);

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).not.toMatch(/sign in again/i);
  });

  it('control: a JSON:API 401 is still an expired session', async () => {
    const r = await healthcheck(
      () =>
        ({
          ok: false,
          status: 401,
          statusText: 'Unauthorized',
          headers: new Headers({ 'content-type': 'application/vnd.api+json' }),
          text: async () => JSON.stringify({ errors: [{ status: '401', title: 'Unauthorized' }] }),
        }) as unknown as Response,
    );

    expect(r.error?.kind).toBe('session_expired');
  });
});
